```{r knit-setting-def, eval = TRUE, include=FALSE}
# def functions used everywhere in this doc
knitr::opts_chunk$set(eval = TRUE, include = FALSE)
```

```{r def-issue-con}
issue_con <- function(service_name) {
    # assume you are using config package and Postgres
    crd <- config::get(file = "./_config.yml")
    DBI::dbConnect(
        drv = RPostgres::Postgres(),
        host = crd$host,
        port = crd$port,
        dbname = crd$dbname,
        user = crd$user,
        password = crd$password
    )
}
```

```{r def-release-con}
release_cons <- function(search_from = ls(".GlobalEnv"), except = NULL) {
    purrr::map_chr(
        .x = search_from %>% base::setdiff(except),
        .f = function(x) {
            ret <- ""
            if (x %>% get() %>%
                {
                    inherits(., "PqConnection") & length(.) == 1
                }) {
                ret <- tryCatch(
                    {
                        x %>%
                            get() %>%
                            DBI::dbDisconnect()
                        return(x)
                    },
                    error = function(e) {
                        msg <- paste("Invalid PqConnection class object is provided:", x)
                        message(msg)
                    },
                    warning = function(e) {
                        return("")
                    }
                )
            }
            return(ret)
        }
    ) %>% .[. != ""]
}
```

```{r refresh-con, eval=FALSE}
release_cons()
con <- issue_con()
```