```{r knit-setting-about, eval = TRUE, include=FALSE}
# knit setting for this file
knitr::opts_chunk$set(
    eval = TRUE,
    include = TRUE,
    echo = TRUE,
    warning = FALSE,
    collapse = TRUE
)
```

# dbplyr とは {#about-dbplyr}

[dbplyr 公式](https://dbplyr.tidyverse.org/index.html).

## 概要 {#about}

dbplyr とは, dplyr が DB からデータを得て加工処理を行う際にバックエンドとして働くパッケージ. dbplyr が影で働いてくれるおかげで, DB 上のデータを手元にダウンロードしていないにも関わらず, あたかも手元にあるかのように, 手慣れた dplyr の文法でデータ加工処理を行うことができる. 

dbplyr は, dplyr の文法で書いたデータ加工処理を接続先の DBMS に合わせた適切な SQL クエリに翻訳する.
翻訳されたクエリは DB との通信を担当する DBI (Database Interface) パッケージを通して実行され, その実行結果は参照としてローカルに返される.
これは, SQL の実行結果が常に実データとして手元にダウンロードされる DBI とは対照的である.

たとえば, [R042 - dbplyrでデータサイエンス100本ノック](https://shena4746.github.io/datascience-100knocks-preprocess-R/#r-042) は見た目は普通の R コードだが, SQL に翻訳されてサーバー側で実行され, その結果は参照として返されている. そのため, テーブルの表示が通常の tibble などと少しだけ異なるが, dplyr と大きく異なる印象は受けないだろう. 実際, **翻訳が上手く働く限り**, dbplyr を意識する必要はほとんどなく, dplyr だと思って書くことができる.

## Pros & Cons {#pros-cons}

直接 SQL を書くのではなく dbplyr を使う長所と短所を整理しておく.

- 長所
	- R - SQL 間の, いわゆる言語またぎが減る
	- SQL の方言に関わらず, dplyr による統一的な書き方ができる
	- 多くの場合, コードがより簡潔になる
- 短所
	- SQL に比べて(ユーザーと?)文献が少ない
	- 新たに利用するパッケージについて学習コストが発生する
		- dbplyr, DBI などのパッケージ自体の学習
		- dbplyr が翻訳可能な R コードの分類

特に, 翻訳不可能なコードが存在することは強調しておきたい. たとえば, `base::quantile` は非常に限定的なケースでしか翻訳できないし, `dplyr::group_modify` は全く翻訳不可能である.

## 標準的な作業フロー {#work-flow}

以下は, dbplyr を利用する際の典型的な作業フローの概要. 教科書的には, 次のようになる.

- **接続**: DBI と 接続先 DBMS に対応した専用パッケージ (e.g., RPostgres, RSQLite) で接続を確立.
- **テーブルへの参照取得**: 接続した DB 上のテーブルへの参照を取得.
- **処理内容の作成**: 参照先のテーブルに対して, dplyr の文法でデータ加工処理を書く.
- **SQLへの翻訳 (自動実行)**: dbplyr がその処理内容を SQL に変換する.
- **SQL の実行 (自動実行)**: DBI 等のバックエンドパッケージがその SQL を実行し, 結果への参照を返す.
- **処理済テーブルの作成 (任意)**: 加工を終えたデータを新たなテーブルとして DB に書き込む.

しかし, 現実には [Pros & Cons](#pros-cons) で言及した翻訳問題に直面することが多々ある. その際は, サイズが十分小さくなるまで加工したデータをローカルマシンにダウンロードし, 通常の R での加工処理に帰着させる方法をよく取る. この場合, 先述の作業フローに次が追加される.

- **データのダウンロード**: DB 上のデータを dplyr で手元にダウンロードする.
- **ローカルでのデータ加工**: ダウンロードデータを通常のローカルデータとしてさらに加工する. パッケージ含め任意のR関数が自由に使える.
- **データのアップロード (任意)**: ローカルでの加工を終えたデータを DB 上にアップロードする.

もちろん, これは R 上で作業を続けるという場合のフローである. そうではなく, SQL で書くことに切り替えるという選択肢も当然存在する. なお, 本稿では詳しく触れないが, DBI には R 上から SQL を発行して実行するメソッドも存在する. 必要に応じて [参考文献](ref) や公式ドキュメントを参照されたい.